### PR TITLE
Fix reflection warnings

### LINKED ISSUE #537: Reflective calls
There's about 85 reflection warnings when loading `overtone.live`. Many of them are in critical areas like communicating with SuperCollider.

I have a fork where I've successfully resolved them, I can submit a PR and extract those changes.

```clojure
Reflection warning, overtone/helpers/doc.clj:15:25 - reference to field length can't be resolved.
Reflection warning, overtone/helpers/doc.clj:43:17 - reference to field length can't be resolved.
Reflection warning, overtone/helpers/doc.clj:44:11 - call to method endsWith can't be resolved (target class is unknown).
Reflection warning, overtone/osc/util.clj:19:16 - call to method contains can't be resolved (target class is unknown).
Reflection warning, overtone/osc/util.clj:74:36 - call to method startsWith can't be resolved (target class is unknown).
Reflection warning, overtone/osc/util.clj:75:20 - call to method substring can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:8:20 - reference to field position can't be resolved.
Reflection warning, overtone/osc/encode.clj:10:7 - call to method put can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:15:13 - reference to field getBytes can't be resolved.
Reflection warning, overtone/osc/encode.clj:15:3 - call to method put can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:16:3 - call to method put can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:22:3 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:23:3 - call to method put can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:34:16 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:34:28 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:37:8 - call to method putLong can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:50:12 - call to method putDouble can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:49:12 - call to method putFloat can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:48:12 - call to method putLong can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:47:12 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:50:12 - call to method putDouble can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:49:12 - call to method putFloat can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:48:12 - call to method putLong can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:47:12 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:68:21 - reference to field position can't be resolved.
Reflection warning, overtone/osc/encode.clj:69:7 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:75:21 - reference to field position can't be resolved.
Reflection warning, overtone/osc/encode.clj:76:9 - call to method position can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:77:9 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:78:9 - call to method position can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:68:21 - reference to field position can't be resolved.
Reflection warning, overtone/osc/encode.clj:69:7 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:75:21 - reference to field position can't be resolved.
Reflection warning, overtone/osc/encode.clj:76:9 - call to method position can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:77:9 - call to method putInt can't be resolved (target class is unknown).
Reflection warning, overtone/osc/encode.clj:78:9 - call to method position can't be resolved (target class is unknown).
Reflection warning, overtone/at_at.clj:15:3 - reference to field printStackTrace can't be resolved.
Reflection warning, overtone/at_at.clj:211:16 - call to java.util.concurrent.ScheduledThreadPoolExecutor ctor can't be resolved.
Reflection warning, overtone/osc/peer.clj:36:24 - reference to field unregisterAllServices can't be resolved.
Reflection warning, overtone/osc/peer.clj:37:24 - reference to field close can't be resolved.
Reflection warning, overtone/osc/peer.clj:48:26 - call to method unregisterService can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:62:26 - call to method registerService can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:122:43 - reference to field getHostString can't be resolved.
Reflection warning, overtone/osc/peer.clj:123:43 - reference to field getPort can't be resolved.
Reflection warning, overtone/osc/peer.clj:232:40 - reference to field socket can't be resolved.
Reflection warning, overtone/osc/peer.clj:236:40 - reference to field socket can't be resolved.
Reflection warning, overtone/osc/peer.clj:320:3 - call to method write can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:340:26 - call to java.net.InetSocketAddress ctor can't be resolved.
Reflection warning, overtone/osc/peer.clj:345:3 - call to method write can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:362:28 - call to java.net.InetSocketAddress ctor can't be resolved.
Reflection warning, overtone/osc/peer.clj:389:3 - call to method write can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:397:3 - reference to field close can't be resolved.
Reflection warning, overtone/osc/peer.clj:401:9 - call to method join can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:402:9 - reference to field join can't be resolved.
Reflection warning, overtone/osc/peer.clj:405:9 - call to method join can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:406:9 - reference to field join can't be resolved.
Reflection warning, overtone/osc/peer.clj:427:14 - call to java.net.InetSocketAddress ctor can't be resolved.
Reflection warning, overtone/osc/peer.clj:449:11 - call to method endsWith can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:451:15 - call to method startsWith can't be resolved (target class is unknown).
Reflection warning, overtone/osc/peer.clj:469:19 - call to method get can't be resolved (target class is unknown).
Reflection warning, overtone/helpers/lib.clj:339:11 - call to method replaceAll can't be resolved (target class is unknown).
Reflection warning, overtone/helpers/lib.clj:340:11 - call to method replaceAll can't be resolved (target class is unknown).
Reflection warning, overtone/helpers/lib.clj:341:11 - call to method replaceAll can't be resolved (target class is unknown).
Reflection warning, overtone/helpers/lib.clj:342:11 - call to method replaceAll can't be resolved (target class is unknown).
Reflection warning, overtone/helpers/lib.clj:343:11 - reference to field toLowerCase can't be resolved.
Reflection warning, overtone/helpers/lib.clj:372:30 - call to method contains can't be resolved (target class is unknown).
Reflection warning, overtone/helpers/file.clj:411:9 - call to static method copy on java.nio.file.Files can't be resolved (argument types: java.nio.file.Path, java.nio.file.Path, java.nio.file.CopyOption).
Reflection warning, overtone/helpers/file.clj:443:10 - call to static method sleep on java.lang.Thread can't be resolved (argument types: unknown).
Reflection warning, overtone/helpers/file.clj:454:16 - call to static method sleep on java.lang.Thread can't be resolved (argument types: java.lang.Number).
Reflection warning, overtone/helpers/file.clj:465:16 - call to static method sleep on java.lang.Thread can't be resolved (argument types: unknown).
Reflection warning, overtone/libs/handlers.clj:208:7 - call to method execute can't be resolved (target class is unknown).
Reflection warning, overtone/libs/handlers.clj:223:7 - call to method execute can't be resolved (target class is unknown).
Reflection warning, overtone/libs/event.clj:38:16 - reference to field take can't be resolved.
Reflection warning, overtone/libs/event.clj:65:22 - call to java.lang.Thread ctor can't be resolved.
Reflection warning, overtone/libs/event.clj:78:3 - call to method put can't be resolved (target class is unknown).
Reflection warning, overtone/libs/event.clj:147:7 - call to method put can't be resolved (target class is unknown).
Reflection warning, overtone/libs/event.clj:186:7 - call to method put can't be resolved (target class is unknown).
Reflection warning, overtone/libs/event.clj:195:7 - call to method put can't be resolved (target class is unknown).
Reflection warning, overtone/libs/event.clj:195:7 - call to method put can't be resolved (target class is unknown).
buffer.clj:310 recur arg for primitive local: n_vals_read is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: n-vals-read
buffer.clj:355 recur arg for primitive local: position is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: position
buffer.clj:376 recur arg for primitive local: idx is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: idx
chance.clj:51 recur arg for primitive local: cumulative is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: cumulative
Reflection warning, overtone/music/pitch.clj:143:49 - call to java.lang.Integer ctor can't be resolved.
debug.clj:123 recur arg for primitive local: result is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: result
midi.clj:362 recur arg for primitive local: cur_time is not matching primitive, had: Object, needed: long
Auto-boxing loop arg: cur-time
```

### PR DESCRIPTION
**Pull request by frenchy64**
Close #537

I was conservative about autoboxing warnings based on my reading of https://clojure.org/reference/java_interop#optimization

The remaining warnings are fixed by https://github.com/overtone/at-at/pull/26

overtone.studio.event doesn't compile so I fixed it. I also fixed a different bug where a list was being tested for `integer?`.

```clojure
user=> (set! *warn-on-reflection* true)
true
user=> (use 'overtone.live)
--> Loading Overtone...
Reflection warning, overtone/at_at.clj:15:3 - reference to field printStackTrace can't be resolved.
Reflection warning, overtone/at_at.clj:211:16 - call to java.util.concurrent.ScheduledThreadPoolExecutor ctor can't be resolved.
```

### CODE REVIEW

File: src/overtone/osc/peer.clj [hunk 1]
```diff
@@ -385,25 +388,29 @@
...
 (defn close-peer
-  "Close a peer, also works for clients and servers."
-  [peer & wait]
-  (when (:zero-conf-name peer)
-    (unregister-zero-conf-service (:port peer)))
-  (dosync (ref-set (:running? peer) false))
-  (.close (:chan peer))
-  (when wait
-    (if (:listen-thread peer)
-      (if (integer? wait)
```
Comment (frenchy64) [inline src/overtone/osc/peer.clj:400]: This code never worked. `integer?` on an arguments list is false.

**Comment by plexus** [comment]
Fantastic!

**Comment by plexus** [comment]
Released in [v0.15.3295](https://github.com/overtone/overtone/releases/tag/v0.15.3295)

```clj
[overtone/overtone "0.15.3295"]                 ;; deps.edn
{overtone/overtone {:mvn/version "0.15.3295"}}  ;; project.clj
```
